name 'awesome_customers'
maintainer 'Austin Heiman'
maintainer_email 'atheimanksu@gmail.com'
license 'all_rights'
description 'Installs/Configures awesome_customers'
long_description 'Installs/Configures awesome_customers'
version '0.3.2'

depends 'apache2', '~> 3.1.0'
depends 'iptables', '~> 1.0.0'
depends 'selinux', '~> 0.9.0'
depends 'mysql2_chef_gem', '~> 1.0.1'
depends 'mysql', '~> 6.0.22'
depends 'database', '~> 4.0.6'
